<?php

namespace ContainerBhDMDj1;

use Symfony\Component\DependencyInjection\Argument\RewindableGenerator;
use Symfony\Component\DependencyInjection\ContainerInterface;
use Symfony\Component\DependencyInjection\Exception\RuntimeException;

/**
 * @internal This class has been auto-generated by the Symfony Dependency Injection Component.
 */
class getModeratorDashboardControllerService extends App_KernelDevDebugContainer
{
    /**
     * Gets the public 'App\Controller\Admin\ModeratorDashboardController' shared autowired service.
     *
     * @return \App\Controller\Admin\ModeratorDashboardController
     */
    public static function do($container, $lazyLoad = true)
    {
        include_once \dirname(__DIR__, 4).'/vendor/symfony/framework-bundle/Controller/AbstractController.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Contracts/Controller/DashboardControllerInterface.php';
        include_once \dirname(__DIR__, 4).'/vendor/easycorp/easyadmin-bundle/src/Controller/AbstractDashboardController.php';
        include_once \dirname(__DIR__, 4).'/src/Controller/Admin/ModeratorDashboardController.php';

        $container->services['App\\Controller\\Admin\\ModeratorDashboardController'] = $instance = new \App\Controller\Admin\ModeratorDashboardController();

        $instance->setContainer(($container->privates['.service_locator.mV6ntiS'] ?? $container->load('get_ServiceLocator_MV6ntiSService'))->withContext('App\\Controller\\Admin\\ModeratorDashboardController', $container));

        return $instance;
    }
}
